Add timer for tests
Vason-err/TestGuru pull request #16
Opened 2021-07-15 23:43 UTC by Vason-err

2021-07-16 08:58 UTC, VidgarVii requested changes

2021-07-16 08:58 UTC, VidgarVii commented on app/controllers/test_passages_controller.rb
> +  before_action :check_timer, only: [:show]
колбеки для 1 экшена не пишут.

2021-07-16 08:58 UTC, VidgarVii commented on app/controllers/test_passages_controller.rb
> +      redirect_to result_test_passage_path(@test_passage) unless @test_passage.timer_valid?
не совсем понятно зачем тут валидировать таймер? тут явно беда с неймингом

2021-07-16 08:58 UTC, VidgarVii commented on app/javascript/utilities/timer.js
> +    this.timer = document.querySelector(".timer")
лучше вообще не создавать объект Timer если не установлен таймер для теста

Сейчас этот класс используется для всех страниц

2021-07-16 08:58 UTC, VidgarVii commented on app/javascript/utilities/timer.js
> +      function submitAnswerForm() {
функция в функции? убирай. разбивай код на нормальные методы

2021-07-16 08:58 UTC, VidgarVii commented on app/javascript/utilities/timer.js
> +export default Timer
1 нет пустой строки
2 экспортировать класс можно сразу при объявлении класса

2021-07-17 06:30 UTC, VidgarVii requested changes

2021-07-17 06:30 UTC, VidgarVii commented on app/javascript/packs/application.js
> +  if (timer) { new Timer(timer) }
if (timer) new Timer(timer)

2021-07-17 06:30 UTC, VidgarVii commented on app/javascript/utilities/timer.js
> +  static submitAnswerForm() {
почему метод должен быть статичным ?

2021-07-17 10:57 UTC, Vason-err commented on app/javascript/utilities/timer.js
> +  static submitAnswerForm() {
Иначе из-за нарушения контекста его невозможно вызвать, раньше можно было присвоить this другой переменной по типу var self = this и пользоваться этим, теперь это не работает, а другого решения я не нашел, метод просто не видит этот submitAnswerForm, он ищет такую функцию внутри себя, и она для этого метода оказывается undefined, я смотрел на это в консоли, он ее просто не находит, насколько я понял именно из-за этих самых this, которые в js работают немного иначе

2021-07-17 10:57 UTC, merged